### ISSUE TITLE
format_proxy function suggestion

### ISSUE THREAD

**Issue by efenatuyo** [maxhithere/CapBypassWrapped#8]
Instead of using regex you can just use split(":") and check the Len which is less consuming and faster

**Comment by maxhithere** [comment]
There’s like a 0.01 ms difference I wouldn’t say this is faster, just a different method

**Comment by efenatuyo** [comment]
Makes it much more readable regex is really not reader in that part but you can keep it

**Comment by maxhithere** [comment]
it’s the same amount of lines I don’t get what you’re saying
